apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: microservices-demo
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql.microservices-demo.svc.cluster.local:3306/orders_db
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
