apiVersion: v1
kind: Secret
metadata:
  name: harbor-pull
  namespace: microservices-demo
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "44.199.252.87:80": {
          "username": "admin",
          "password": "StrongHarborPass123",
          "auth": "YWRtaW46U3Ryb25nSGFyYm9yUGFzczEyMw=="
        }
      }
    }
